# Generated by Django 4.0.2 on 2022-02-07 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ADMIN', 'Admin'), ('AUTHOR', 'Author')], default='AUTHOR', max_length=10)),
                ('host', models.URLField()),
                ('displayName', models.CharField(max_length=50)),
                ('github', models.CharField(max_length=100)),
                ('profileImage', models.URLField()),
            ],
        ),
    ]
