# Generated by Django 4.0.1 on 2022-02-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(blank=True),
        ),
    ]
