# Generated by Django 4.0.2 on 2022-02-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_displayname_alter_author_github_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='type',
            field=models.CharField(choices=[('admin', 'Admin'), ('author', 'Author')], default='author', max_length=10),
        ),
    ]
