# Generated by Django 4.0.2 on 2022-02-13 07:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0004_alter_author_type'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentsSrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='comments', editable=False, max_length=8)),
                ('page', models.IntegerField(default=1, editable=False)),
                ('size', models.IntegerField(default=5, editable=False)),
                ('comments', models.ManyToManyField(blank=True, related_name='comments', to='comment.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='post', editable=False, max_length=4)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('source', models.URLField(blank=True)),
                ('origin', models.URLField(blank=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('contentType', models.CharField(choices=[('text/markdown', 'Common Mark'), ('text/plain', 'Utf8'), ('application/base64', 'App Base64'), ('image/png;base64', 'Embeded Png'), ('image/jpeg;base64', 'Embeded Jpge'), ('text/html', 'Html Text')], max_length=20)),
                ('content', models.TextField(blank=True)),
                ('categories', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), blank=True, default=list, null=True, size=None)),
                ('count', models.IntegerField(default=0)),
                ('comment', models.URLField(blank=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('FRIENDS', 'Friends')], max_length=7)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='author.author')),
                ('commentsSrc', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='commentsSrc', to='post.commentssrc')),
            ],
        ),
        migrations.AddField(
            model_name='commentssrc',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
